made `withStateThread` parameterized at Plutarch
Liqwid-Labs/liqwid-plutarch-extra pull request #103
Opened 2022-10-14 02:49 UTC by SeungheonOh

2022-10-14 14:25 UTC, peter-mlabs requested changes
needs haddocks, sinces, changelog, and cabal version bump, but otherwise looks fine

2022-10-16 22:45 UTC, kozross requested changes
The naming seems a bit off. Also, the docs should indicate clearly what the two different functions differ in.

Also what @peter-mlabs said.

2022-10-25 21:20 UTC, peter-mlabs approved these changes

2022-10-25 21:21 UTC, kozross approved these changes

2022-10-25 21:56 UTC, merged