use `Plutarch.Prelude`
Liqwid-Labs/liqwid-plutarch-extra pull request #57
Opened 2022-08-12 17:51 UTC by SeungheonOh

2022-08-12 17:56 UTC, chfanghr approved these changes
🚀

2022-08-13 15:22 UTC, peter-mlabs commented
@kozross, how do you feel about allowing `import Plutarch.Prelude` without an explicit import list, or the way we do for dApps with `mixins` and an implicit prelude?

2022-08-13 18:21 UTC, kozross commented
I feel that `Plutatch.Prelude` is not a full replacement for the `base` one, and therefore should be treated like any other import.

If we want a replacement `Prelude`, which may or may not include identifiers coming from Plutarch, that's a separate story IMHO, since there's definitely some disagreement over what it should, and shouldn't, include. I certainly have some thoughts of my own, but they'd need a full writeup.

2022-08-13 19:10 UTC, peter-mlabs commented
FTR, in all the non Liqwid Lib's repos (as well as [plutus-scaffold](https://github.com/mlabs-haskell/plutus-scaffold/blob/master/onchain/template-project.cabal), we use

```
  mixins:
    base hiding (Prelude),
    pprelude (PPrelude as Prelude)
``` 

in the  cabal and

```hs
module PPrelude (
  module Prelude,
  module Plutarch.Prelude,
) where

import Plutarch.Prelude
import Prelude
```

as `PPrelude`. I think this would be good to adopt if there's no strong opposition.

2022-08-14 04:36 UTC, kozross commented
@peter-mlabs I'm not opposed - there are no name clashes or major surprises, and the Plutarch prelude is its intended (primary) API.

2022-08-14 19:06 UTC, SeungheonOh commented
Okay, It seems like we are going to use `PPrelude` I'll update this PR.

2022-08-14 21:27 UTC, kozross requested changes

2022-08-14 21:27 UTC, kozross commented on src/Plutarch/Extra/FixedDecimal.hs
>  import Plutarch.Num (PNum (..))
A bit stale, but proper imports.

2022-08-14 21:27 UTC, kozross commented on src/Plutarch/Extra/FixedDecimal.hs
>      AdditiveMonoid (..),
Also here.

2022-08-14 21:27 UTC, kozross commented on src/Plutarch/Extra/FixedDecimal.hs
>      DerivePlutusType (..),
And here.

2022-08-14 21:27 UTC, kozross commented on src/Plutarch/Extra/List.hs
> +    PListLike (..),
Proper imports please.

2022-08-14 21:27 UTC, kozross commented on src/Plutarch/Extra/Map/Sorted.hs
> +    PListLike (..),
Proper imports.

2022-08-14 21:27 UTC, kozross commented on src/Plutarch/Extra/These.hs
> +    PPartialOrd (..),
Proper imports.

2022-08-14 22:03 UTC, SeungheonOh commented
Okay using mix-ins looks so much cleaner.

2022-08-15 14:16 UTC, peter-mlabs commented
Added `-Wmissing-import-lists` to the cabal and `{-# OPTIONS_GHC -Wno-missing-import-lists #-}` to the files with `import Prelude hiding (..,)` statements.

2022-08-15 14:32 UTC, peter-mlabs approved these changes
All should be good now, thanks!

2022-08-15 19:23 UTC, kozross requested changes

2022-08-15 19:23 UTC, kozross commented on src/Plutarch/Extra/AssetClass.hs
> +{-# OPTIONS_GHC -Wno-missing-import-lists #-}
A comment explaining why this is off would be good I think, for future reference if nothing else.

2022-08-15 19:23 UTC, kozross commented on src/Plutarch/Extra/Bind.hs
> +{-# OPTIONS_GHC -Wno-missing-import-lists #-}
Same here.

2022-08-15 19:23 UTC, kozross commented on src/Plutarch/Extra/Map.hs
> +{-# OPTIONS_GHC -Wno-missing-import-lists #-}
Also here.

2022-08-15 19:23 UTC, kozross commented on src/Plutarch/Extra/Traversable.hs
> +{-# OPTIONS_GHC -Wno-missing-import-lists #-}
And here.

2022-08-15 19:23 UTC, kozross commented on test/Spec.hs
> +-- import qualified Spec.Extra.MultiSig as MultiSig
Should this be removed?

2022-08-15 19:23 UTC, kozross commented on test/Spec/Extra/Map/Sorted.hs
> +import Plutarch.Api.V1.AssocMap (KeyGuarantees (..), PMap)
Wildcard imports shouldn't be used.

2022-08-15 23:43 UTC, kozross requested changes

2022-08-15 23:43 UTC, kozross commented on src/Plutarch/Extra/FixedDecimal.hs
>      AdditiveMonoid (..),
Imports.

2022-08-15 23:43 UTC, kozross commented on src/Plutarch/Extra/FixedDecimal.hs
>      AdditiveSemigroup (..),
Also here.

2022-08-15 23:43 UTC, kozross commented on src/Plutarch/Extra/Identity.hs
>      PIdentity (..),
Imports.

2022-08-16 19:29 UTC, kozross approved these changes

2022-08-16 19:56 UTC, merged