Improve efficiency of the `MultiSig` module
Liqwid-Labs/liqwid-plutarch-extra pull request #70
Opened 2022-08-22 10:42 UTC by chfanghr

2022-08-22 15:05 UTC, SeungheonOh approved these changes
This seems like a good upgrade for `MultiSig`! Can you change the PR name to address that `MultiSig` is now generic? It's more than a efficiency improvement of it. 

LGTM.

2022-08-22 19:15 UTC, kozross requested changes

2022-08-22 19:15 UTC, kozross commented on src/Plutarch/Extra/MultiSig.hs
> +validatedByMultisig :: forall (s :: S). MultiSig -> Term s (PMultiSigContext :--> PBool)
Signature change, so the `since` should be bumped too.

2022-08-22 19:15 UTC, kozross commented on src/Plutarch/Extra/MultiSig.hs
> +pvalidatedByMultisig :: forall (s :: S). Term s (PMultiSig :--> PMultiSigContext :--> PBool)
Same here.

2022-08-24 19:05 UTC, kozross approved these changes

2022-08-24 19:19 UTC, merged