Added Extra.IsData module
Liqwid-Labs/liqwid-plutarch-extra pull request #9
Opened 2022-06-17 17:55 UTC by t1lde

- `ProductIsData` & the corresponding `PConstantViaDataList` for deriving ToData/FromData/PLift/PConstant/PIsData for record types using the List constructor
- `EnumIsData` & the corresponding `PEnumData` for deriving ToData/FromData/PLift/PConstant/PIsData for Enum types using the PInteger constructor
- `pmatchEnum` & `pmatchEnumFromData` helpers for enums

2022-06-17 18:14 UTC, emiflake requested changes
I've been waiting for this to land. Great stuff. A few doc remarks. Content-wise it looks fine.

2022-06-17 18:14 UTC, emiflake commented on src/Plutarch/Extra/IsData.hs
> +-- | Wrapper for deriving 'ToData', 'FromData' using an Integer representation via 'Enum'
Please add `@since` tagging to all of the added terms/types.

2022-06-17 18:14 UTC, emiflake commented on src/Plutarch/Extra/IsData.hs
> +
Even here.

2022-06-17 18:14 UTC, emiflake commented on src/Plutarch/Extra/IsData.hs
> +-- | Generically convert a Product-Type to 'BuiltinData' with the 'List' repr
Nitpick, but. When it comes to haddock docstrings, we've been ending them with a period everywhere.

2022-06-20 09:25 UTC, t1lde commented
fixed the comments - I think I got everything. 
Is there something to be done for CI (failing on the cachix key)?

2022-06-20 14:17 UTC, merged