Dropped Tag from AssetClass types
Liqwid-Labs/liqwid-plutarch-extra pull request #95
Opened 2022-10-04 21:24 UTC by SeungheonOh

2022-10-04 23:04 UTC, kozross approved these changes

2022-10-04 23:18 UTC, SeungheonOh commented
Please don't merge this yet. I'm working on liqwid side simultaneously and I might need to add some more utilities.

2022-10-05 02:11 UTC, SeungheonOh commented
PR is ready to go. 

Liqwid-onchain has PR ready for this PR. https://github.com/mlabs-haskell/liqwid-onchain/pull/179

2022-10-05 13:35 UTC, peter-mlabs requested changes
looks good overall.

Need to updated some `since`s, especially where you only deleted the tag.

Also, in some haddock comments where you've written `` `foo` ``, it should be `"foo"`, so that we can get haddock linking.

2022-10-05 13:35 UTC, peter-mlabs commented on src/Plutarch/Extra/AssetClass.hs
>   @since 3.9.0
needs a version bump, since the type changed, right?

2022-10-05 13:35 UTC, peter-mlabs commented on src/Plutarch/Extra/AssetClass.hs
> +    ( -- | @since 3.9.0
versions for these derivations should be 3.10.0

2022-10-05 13:35 UTC, peter-mlabs commented on src/Plutarch/Extra/AssetClass.hs
> +data PAssetClass (s :: S) = PAssetClass
version bump

2022-10-05 13:35 UTC, peter-mlabs commented on src/Plutarch/Extra/AssetClass.hs
>  -- | @since 3.9.0
update since

2022-10-05 13:35 UTC, peter-mlabs commented on src/Plutarch/Extra/AssetClass.hs
>  -- | @since 3.9.0
update since

2022-10-05 13:35 UTC, peter-mlabs commented on src/Plutarch/Extra/Value.hs
> +{- | Tagged version of `passetClassValueOf'`.
use quotes here to get haddock linking

2022-10-05 17:10 UTC, kozross commented
@peter-mlabs It's actually 'foo'. Single quotes create Haddock links.

2022-10-10 12:57 UTC, peter-mlabs approved these changes
Looks good now, thanks @SeungheonOh!

2022-10-10 12:57 UTC, merged